### PR TITLE
updated environment variable fetch so if doesn't exist, error is raised

### PR DESCRIPTION
**Pull request by oliverangelil**

### CODE REVIEW

**Comment by RicSegundo** [comment]
Waiting for checks passing and will approve

**Comment by oliverangelil** [comment]
@RicSegundo when I run the unit tests locally they work. Only when I push to github they fail with KeyError, so I don't know if [this](https://stackoverflow.com/a/54479162/5392289) solution will help us...

**Review by RicSegundo — APPROVED** [review]
Added the env variables on the main.yml file

**Comment by RicSegundo** [comment]
The solution to this problem is at https://stackoverflow.com/questions/66593382/how-to-pass-secrets-from-github-actions-to-python-environ-variables

**Pull request merged**
